{% set data= load_setup_py_data() %}
package:
  name: ts-watcher
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build
    - ts-idl
    - ts-salobj
  source_files:
    - python
    - bin
    - tests
    - schema
    - setup.cfg
  commands:
    - pytest

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
