{% set data= load_setup_py_data() %}
package:
  name: ts-watcher
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - command_watcher = lsst.ts.watcher:command_watcher
    - run_watcher = lsst.ts.watcher:run_watcher

test:
  requires:
    - aiohttp >=3.8,<4.0
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-utils
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - aiohttp >=3.8,<4.0
    - ts-idl
    - ts-utils
    - ts-salobj
